WebOneApp/Models/Resturant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebOneApp.Models
{
    public class Resturant
    {
        public Resturant()
        {
            imgPath = "~/Content/user.png";
            meals = new Dictionary<string,List<Meal>>();
            categories = new List<Category>();
            guid = Guid.NewGuid().ToString().Split('-').First();
        }

        [Required]
        public int id { get; set; }
        [Required]
        public string guid { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Image")]
        public string imgPath { get; set; }
        [NotMapped]
        public HttpPostedFileBase imageUpload { get; set; }
        public Dictionary<string,List<Meal>> meals { get; set; }
        public List<Category> categories { get; set; }
    }
}

WebOneApp/Controllers/API/ResturantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using WebOneApp.Models;

namespace WebOneApp.Controllers.API
{
    public class ResturantsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: api/Resturants
        public IQueryable<Resturant> GetResturants()
        {
            return db.Resturants;
        }

        // GET: api/Resturants/5
        [ResponseType(typeof(Resturant))]
        public object GetResturant(string code)
        {
            try
            {
                Resturant resturant = db.Resturants.ToList().First(x => x.guid == code);
                Helper.SortMeals(db.Meals.Where(x => x.resturantId == resturant.id).ToList(), resturant.meals);
                if (resturant == null){
                    return NotFound();
                }

                return Ok(resturant);
            }catch(Exception) {
                return new { Erros = "Could not find resturant" };
            }
            
        }

        // PUT: api/Resturants/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutResturant(int id, Resturant resturant)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != resturant.id)
            {
                return BadRequest();
            }

            db.Entry(resturant).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ResturantExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Resturants
        [ResponseType(typeof(Resturant))]
        public IHttpActionResult PostResturant(Resturant resturant)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Resturants.Add(resturant);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = resturant.id }, resturant);
        }

        // DELETE: api/Resturants/5
        [ResponseType(typeof(Resturant))]
        public IHttpActionResult DeleteResturant(int id)
        {
            Resturant resturant = db.Resturants.Find(id);
            if (resturant == null)
            {
                return NotFound();
            }

            db.Resturants.Remove(resturant);
            db.SaveChanges();

            return Ok(resturant);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool ResturantExists(int id)
        {
            return db.Resturants.Count(e => e.id == id) > 0;
        }
    }
}

WebOneApp/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebOneApp.Models;

namespace WebOneApp.Controllers
{
    public class MealsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Meals
        public ActionResult Index()
        {
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            return View(db.Meals.ToList());
        }

        // GET: Meals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // GET: Meals/Create
        public ActionResult Create()
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            return View();
        }

        // POST: Meals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,resturantId,name,price,description,category,startDate,endDate,imgPath")] Meal meal)
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            ViewBag.resturantId = new SelectList(db.Resturants, "id", "name");
            if (ModelState.IsValid)
            {
                db.Meals.Add(meal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(meal);
        }

        // GET: Meals/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,resturantId,name,price,description,category,startDate,endDate,imgPath")] Meal meal)
        {
            ViewBag.category = new SelectList(Helper.getCategoryNames(db.Categories.ToList()));
            if (ModelState.IsValid)
            {
                db.Entry(meal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(meal);
        }

        // GET: Meals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meal meal = db.Meals.Find(id);
            db.Meals.Remove(meal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebOneApp/Controllers/ResturantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebOneApp.Models;

namespace WebOneApp.Controllers
{
    public class ResturantsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Resturants
        public ActionResult Index()
        {
            return View(db.Resturants.ToList());
        }

        // GET: Resturants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resturant resturant = db.Resturants.Find(id);
            Helper.SortMeals(db.Meals.Where(x => x.resturantId == resturant.id).ToList(), resturant.meals);
            if (resturant == null)
            {
                return HttpNotFound();
            }
            return View(resturant);
        }

        // GET: Resturants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Resturants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,imgPath")] Resturant resturant)
        {
            if (ModelState.IsValid)
            {
                db.Resturants.Add(resturant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(resturant);
        }

        // GET: Resturants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resturant resturant = db.Resturants.Find(id);
            if (resturant == null)
            {
                return HttpNotFound();
            }
            return View(resturant);
        }

        // POST: Resturants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,imgPath")] Resturant resturant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resturant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(resturant);
        }

        // GET: Resturants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resturant resturant = db.Resturants.Find(id);
            if (resturant == null)
            {
                return HttpNotFound();
            }
            return View(resturant);
        }

        // POST: Resturants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resturant resturant = db.Resturants.Find(id);
            db.Resturants.Remove(resturant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebOneApp/Views/Resturants/Create.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Create";
}

<h4>Create</h4>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Resturant</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.imgPath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.imgPath, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.imgPath, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
    <div class="col-md-6">
        <input type="text" class="form-control" />
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebOneApp/Views/Resturants/Delete.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resturant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayFor(model => model.guid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imgPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imgPath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebOneApp/Views/Resturants/Details.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Details";
}

<h2>@Model.name</h2>


@foreach (var meal in Model.meals)
{
    <div class="row">
        <h4>@meal.Key</h4>
        @foreach (var item in meal.Value)
        {
            <div class="col-md-6">
                <div class="card" style="width:320px;height:300px;">
                    <img style="width:200px;height:150px" class="card-img-top" src=@item.imgPath alt="Card image">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <h4>@item.name</h4>
                            </div>
                            <div col-md-3>
                                <p>@item.price</p>
                            </div>
                        </div>
                        <br />
                        <p class="text-wrap">@item.description</p>
                        <div class="row">
                            <div class="col-md-2">
                                <a class="btn btn-primary" href="@Url.Action("Edit", "Meals", new { id = item.id })">Edit</a>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-primary" href="@Url.Action("Delete", "Meals", new { id = item.id })">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

WebOneApp/Views/Resturants/Edit.cshtml
@model WebOneApp.Models.Resturant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Resturant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imgPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imgPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebOneApp/Views/Resturants/Index.cshtml
@model IEnumerable<WebOneApp.Models.Resturant>

@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<h2>Resturants</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3">
            <div class="card" style="width:320px;height:300px;">
                <img style="width:250px;height:150px" class="card-img-top" src=@item.imgPath alt="Card image">
                <div class="card-body">
                    <h4>@item.name</h4>
                    <div class="row">
                        <div class="col-md-2 btn btn-primary">
                            @Html.ActionLink("Edit", "Edit", new { id = item.id })
                        </div>
                        <div class="col-md-2 btn btn-primary">
                            @Html.ActionLink("Details", "Details", new { id = item.id })
                        </div>
                        <div class="col-md-2 btn btn-primary">
                            @Html.ActionLink("Delete", "Delete", new { id = item.id })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>